### ISSUE TITLE
Screen sudo python... won't execute

### ISSUE THREAD

**Issue by lolwhereami** [ISO-B/pmb-pitft#10]
When I run the command (after everything else works), I don't get any output in terminal or are screen. Here is what the code is showing:

root@MusicBox:~# screen sudo python /root/pmb-pitft/pmb-pitft/ui.py
root@MusicBox:~# dmesg | tail
[   21.084039] smsc95xx 1-1.1:1.0 eth0: hardware isn't capable of remote wakeup
[   21.095910] IPv6: ADDRCONF(NETDEV_UP): eth0: link is not ready
[   22.682048] smsc95xx 1-1.1:1.0 eth0: link up, 100Mbps, full-duplex, lpa 0x45E1
[   22.715451] IPv6: ADDRCONF(NETDEV_CHANGE): eth0: link becomes ready
[   33.170861] watchdog stopped
[   34.694913] smsc95xx 1-1.1:1.0 eth0: hardware isn't capable of remote wakeup
[   35.605459] smsc95xx 1-1.1:1.0 eth0: hardware isn't capable of remote wakeup
[   37.137493] smsc95xx 1-1.1:1.0 eth0: link up, 100Mbps, full-duplex, lpa 0x45E1
[   48.698345] ip_tables: (C) 2000-2006 Netfilter Core Team
[   48.731387] nf_conntrack version 0.5.0 (5944 buckets, 23776 max)

**Comment by ISO-B** [comment]
If you run ```screen -rd``` do you then see something?

**Comment by lolwhereami** [comment]
still see nothing when i run that comment says there is no screen to be detached.

**Comment by lolwhereami** [comment]
since i have the capacitive screen i ran your corrections in the other thread to no avail.

**Comment by ISO-B** [comment]
Did you changed font? I updated installing guide. Near end is help for that.

If that did not help try running ```sudo python /root/pmb-pitft/pmb-pitft/ui.py``` without screen so you can see error message.

**Comment by lolwhereami** [comment]
File "/root/pmb-pitft/pmb-pitft/ui.py", line 176
    signal(SIGALRM, alarm_handler)
         ^
IndentationError: expected an indented block

**Comment by lolwhereami** [comment]
root@MusicBox:~# sudo python /root/pmb-pitft/pmb-pitft/ui.py
Traceback (most recent call last):
  File "/root/pmb-pitft/pmb-pitft/ui.py", line 38, in <module>
    pygame.mouse.set_visible(False)
pygame.error: video system not initialized
root@MusicBox:~#

**Comment by ISO-B** [comment]
Which raspberry pi you are using and which version of PiTFT?
What ```uname -a``` command returns? if it returns "Linux PMB 3.18.5+ ...." I would suggest to try running commands from installing guide again. Start after installing Pi MusicBox part.
